### ISSUE TITLE
Motor "jerks" when launch

### ISSUE THREAD

**Issue by David9696** [roaldlemmens/morph_hw#4]
Hi,

When the morph.launch file is launched, sometimes, the motor is subjected to a big 'jerk' or 'vibrate' and then stopped. I wonder whether this is normal. 

Thanks.

**Comment by roaldlemmens** [comment]
Hi,
Which branch are you using? I also noticed this on my current project. I still need to check if this was caused by the changes I did for the PID control (branch feature/duty_cycle_pid), or newer firmware of the vesc, which may need changes to the vesc_driver. I didn't have this before, using master branch and older firmware vesc.

**Comment by David9696** [comment]
Hi,

I have tried both the master and the duty_cycle_pid branch respectively. But, both of them having this "jerk" behavior during launch. Maybe like what you said it is related to the vesc firmware. I am using the latest vesc firmware. I am not very good in programming. Once you have the fix, I am more than willing to help you to test. 

Thanks.

**Comment by roaldlemmens** [comment]
Hi, I found the cause calling setDetect with no encoder causes this issue. Probably due to changes in the firmware. Will look into that later. Note that the control mechanism of the PID has changed and you may need to tune the PID parameters. There's a document describing how you could do it.
