### ISSUE TITLE
Extension to skid-steering 

### ISSUE THREAD

**Issue by saeedarabi92** [roaldlemmens/morph_hw#5]
I want to extend the robot to skid-steering. Would it be possible by reasonable effort or I need to modify a lot of codes? Which codes should I change?

Thank you in advance

**Comment by roaldlemmens** [comment]
It should be possible with reasonable effort, since some support for skid steering is available in ros_control. See http://wiki.ros.org/diff_drive_controller#Skid_steer and https://github.com/ros-controls/ros_controllers/issues/100 to read more about that. You would have to add the joint controllers in morph_hw.cpp.

**Comment by saeedarabi92** [comment]
> It should be possible with reasonable effort, since some support for skid steering is available in ros_control. See http://wiki.ros.org/diff_drive_controller#Skid_steer and [ros-controls/ros_controllers#100](https://github.com/ros-controls/ros_controllers/issues/100) to read more about that. You would have to add the joint controllers in morph_hw.cpp.


I tried this and I was able to extend the code for skid-steering using your hint. Thanks!
